[project]
name = "voicebot-ai-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-cloud-aiplatform>=1.73.0",
    "google-cloud-speech>=2.28.1",
    "google-cloud-texttospeech>=2.21.1",
    "pyaudio>=0.2.14",
]
